kind: pipeline
name: default

steps:
- name: test
  image: golang
  environment:
    FOO: BAR
  commands:
  - go test ./...
- name: publish-image
  image: plugins/docker
  settings:
      username: eelya
      password: dzdPKubuYmZ8LatDdwFmfqtoqPE823mA
      repo: eelya/zdrone
      tags: DRONE_COMMIT_SHA

