kind: pipeline
name: default

steps:
- name: test
  image: golang
  environment:
    FOO: BAR
  commands:
  - go test ./...
- name: publish-image
  image: plugins/docker
  settings:
      username: eelya
      password: 
        from_secret: docker-registry-pwd
      repo: eelya/zdrone
      tags: latest
