kind: pipeline
name: default

steps:
- name: test
  image: golang
  environment:
    FOO: BAR
  commands:
  - go test ./...

- name: test2
  image: golang
  environment:
    FOO: ZZZ
  commands:
  - echo "boom"
  - go test -v ./...
  


